### ISSUE TITLE
Can't run the example

### ISSUE THREAD

**Issue by danigb** [mauritslamers/presto#5]
Hi,

I decided to give presto a try, and I couldn't run the example.  This is my code (copied from github with some minor fixes):

``` js
var score = {
  staffs: [
    {
      clef: "treble",
      key: "c",
      time: "4/4",
      notes: [
        { name: "c", length: 4, octave: 1 }
      ]
    }
  ]
}

var p = Presto.Score.from('canvasId');
window.setTimeout(function () {
  console.log('render')
  p.parse(score);
  p.notate();
  p.render();
}, 1000);
```

Running this code I get: `Uncaught TypeError: p.notate is not a function`. If I comment the `p.notate();` line, nothing is rendered. I also got a `fontInactive` message.

Thanks,
Dani

**Comment by mauritslamers** [comment]
There have been some changes in the API and I haven't had the time to adjust the docs yet. The experiment.html page shows a working example. I ran the following code in the experiment.html file:

```
var score = {
  staffs: [
    {
      clef: "treble",
      key: "c",
      time: "4/4",
      notes: [
        { name: "c", length: 4, octave: 1 }
      ]
    }
  ]
};

var p = Presto.Score.from('example');
window.setTimeout(function () {
  p.parse(score);
  p.render();
}, 1);
```

and that works. Sorry for the confusion. Please let me know if you still have issues.

**Comment by danigb** [comment]
Thanks. I will try it asap. 👍

**Comment by danigb** [comment]
Sorry I had this issue open so much time. Thanks.
